# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: CmdLine@2
  inputs:
    script: |
      set -v
      cd $(Build.Repository.LocalPath)
      ls
      pwd
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Test'
    publishLocation: 'pipeline'
- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-azure connection'
    regionName: 'us-east-1'
    awsCommand: 'aws'
    awsSubCommand: 's3 cp'
    arguments: '$(Pipeline.Workspace)/build s3://azuretestbucket123/ --recursive'

